mysql:
  image: binhdna/mysql
  ports:
   - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: rootpass
    MYSQL_USER: dbuser
    MYSQL_PASSWORD: userpass
    MYSQL_DATABASE: myimage_db
frontend:
  image: binhdna/node-web-app
  working_dir: /usr/src/app
  ports:
   - "8080:8080"
  links:
   - "mysql"
